version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: uwsgi --http :8000 --wsgi-file src/tennis_score_board/adapters/presentation/wsgi.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://your_healthcheck_url"]
      interval: 1m
      timeout: 30s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://your_healthcheck_url"]
      interval: 1m
      timeout: 30s
      retries: 3

volumes:
  db_data: