"""Flat Match structure

Revision ID: 2deb91427cfe
Revises: 81aa794d6886
Create Date: 2024-08-21 14:22:23.496682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2deb91427cfe'
down_revision: Union[str, None] = '81aa794d6886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('current_game_player1', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('current_game_player2', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('set1_player1', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('set1_player2', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('set2_player1', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('set2_player2', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('set3_player1', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('set3_player2', sa.Integer(), nullable=False))
    op.drop_column('matches', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('score', mysql.JSON(), nullable=False))
    op.drop_column('matches', 'set3_player2')
    op.drop_column('matches', 'set3_player1')
    op.drop_column('matches', 'set2_player2')
    op.drop_column('matches', 'set2_player1')
    op.drop_column('matches', 'set1_player2')
    op.drop_column('matches', 'set1_player1')
    op.drop_column('matches', 'current_game_player2')
    op.drop_column('matches', 'current_game_player1')
    # ### end Alembic commands ###
