"""Update Match.score

Revision ID: 81aa794d6886
Revises: 97398e388851
Create Date: 2024-08-13 13:41:35.499343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81aa794d6886'
down_revision: Union[str, None] = '97398e388851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'score',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'score',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###
